#!/usr/bin/env bash

if [[ $(pgrep -f -o .config/journal) -ne $$ ]]; then
  vim --servername JOURNAL --remote-send "<C-\><C-N>:xall:qall!"
fi

[[ $(date +%-H) -lt 4 ]] && date="yesterday" || date="today"
date=$(date --date=$date +%Y/%m/%d)

mkdir -p "$HOME/saveuriendir/$date"
pushd "$HOME/saveuriendir/$date" > /dev/null

[[ $@ ]] && journal=$@ || journal="main"

journal="$HOME/saveuriendir/$date/${journal%%.md}.md"

if [[ $(vim --version | grep +clientserver) ]]; then
  vim --servername JOURNAL "$journal"
else
  echo Please compile vim with +clientserver option.
fi

[[ -s "$journal" ]] || rm -f "$journal"
