#!/usr/bin/env bash

[[ $(type -t $1) ]] && call_command="$1" && shift
[[ $(vim --version | grep +clientserver) ]] && socket=true

[[ $(date +%-H) -lt 4 ]] && date="yesterday" || date="today"
date=$(date --date=$date +%Y/%m/%d)

journal="${@:-main}"
path="$HOME/saveuriendir/$date/${journal%%.adoc}.adoc"

if [[ $call_command ]]; then
  $call_command "$path"
else
  if [[ $($socket && vim --serverlist | grep JOURNAL) ]]; then
    vim --servername JOURNAL --remote-send "<C-\><C-N>:xall<CR>:qall!<CR>"
  fi

  mkdir -p "$HOME/saveuriendir/$date"
  if [[ $socket ]]; then
    vim --servername JOURNAL "$path"
  else
    vim "$path"
  fi
fi
