#!/usr/bin/env bash

if [[ $(vim --version | grep +clientserver) ]]; then
  vim_in_socket=1
  if [[ $(vim --serverlist | grep JOURNAL) ]]; then
    vim --servername JOURNAL --remote-send "<C-\><C-N>:xall:qall!"
  fi
fi

[[ $(date +%-H) -lt 4 ]] && date="yesterday" || date="today"
date=$(date --date=$date +%Y/%m/%d)

mkdir -p "$HOME/saveuriendir/$date"

journal=${@:-main}
path="$HOME/saveuriendir/$date/${journal%%.md}.md"

[[ $vim_in_socket ]] && vim --servername JOURNAL "$path" || vim "$path"

[[ -s "$path" ]] || rm -f "$path"
