== Installation

[source,bash]
----
git clone git@github.com/Leirda01/point-fichiers.git &&
cd point-fichiers;
./setup.sh
----

On génère des liens symboliques pour chacun des fichiers présents dans le
dépôt, sauf `README.md`, `.git`, `setup.sh` et `run`. Si un fichier est déjà
présent, on en fait une sauvegarde avec le suffixe `~`.

Les liens sont vers `$HOME` pour les fichiers cachés, `$HOME/.config` pour les
autres.

Le dossier `run/` contient tout ce qui sera installé ou généré d’une autre
manière.

== À faire

* `i3`
** [ ] Choisir le nom d’un nouveau workspace et naviguer parmi eux en les désignant par nom.
** [ ] Naviguer parmi les fenêtre en les désignant par nom, indépendamment du workspace dans lequel elle se trouve.
** [ ] Permettre de désigner un workspace sur l’écran secondaire.
** [ ] Créer un workspace par défaut « HUB » pour afficher des infos et des détails à propos de X.
** [ ] Mieux gérér la détection des moniteurs (le faire automatiquement).
** [ ] Gérer les touches spéciales :
*** `wifi`
*** lecture - pause
*** verrouillage
*** calculette
* `vim`
** [ ] Créer mes propres mappings pour le bépo, au lieu de ceux d’un autre.
** [ ] Corriger les mappings conflictuels entre les plugins et la configuration bépo.
* `setup.sh`
** [ ] « ```sed```er » les fichiers qui contiennent des chemins absolus et autres aberrations.

== Sources :

* https://artisan.karma-lab.net/modifier-taille-polices-durxvt[Taille de la police du terminal]
* https://github.com/yaf/dotfiles[Tout dans un « bashrc.d/ »]
* http://bepo.fr/wiki/Mpv[config pour mpv]
