runtime basic.vim

runtime vim-plug.vim
runtime color_space.vim
runtime global_options.vim

call plug#begin('~/.config/vim-plugin')

Plug 'kyoz/purify', { 'rtp': 'vim' }
Plug 'sheoak/vim-bepoptimist'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround', { 'do': 'let g:surround_no_mappings' }
Plug 'vim/killersheep'
Plug 'greyblake/vim-preview'

call plug#end()
