set number
set showcmd
set linebreak
set showbreak=→\ 

set autoindent
set smartindent
set expandtab

set textwidth=80
set tabstop=2
set shiftwidth=2

set hlsearch
set incsearch

set noswapfile
let g:netrw_home="$HOME/.config"

filetype plugin indent on
syntax on

call plug#begin('~/.config/vim-plugin')

Plug 'tpope/vim-sensible'
" Plug 'tpope/vim-surround', { 'do': 'let g:surround_no_mappings' }
Plug 'tpope/vim-repeat'
Plug 'vim/killersheep'
Plug 'greyblake/vim-preview'

call plug#end()

runtime bepo.vim
