#!/usr/bin/env bash

printf """\
Usage: journal OBJECT { COMMAND | help }

OBJECT
write\t\tUse ${EDITOR:=vim} to open a journal page for the current day.
day\t\tUse ${EDITOR:=vim} to read pages of the specified date.
consult \tRead journal pages by name in history.
ls\t\tList all pages in the current day.
rm\t\tRemove page(s) from the current day.
any command\tExecute any command for the current day.
"""
