#!/usr/bin/env bash

printf "Usage: journal [OPTIONS] OBJECT { COMMAND | help }\n\n"

printf "OBJECT\n"
printf "  w[rite]\tUse ${EDITOR:=vim} to open a journal page for the current day.\n"
printf "  c[onsult]\tRead journal pages by name in history.\n"
