#!/usr/bin/env bash

modes="$HOME/.config/journal/"

if [[ ( -f $modes/$1 ) && ( -x $modes/$1 ) ]]; then
  call_mode="$modes/$1" && shift
elif [[ $(type -t $1) ]]; then
  call_command="$1" && shift
fi

[[ $(vim --version | grep +clientserver) ]] && socket="true"

[[ $(date +%-H) -lt 4 ]] && date="yesterday" || date="today"
date=$(date --date=$date +%Y/%m/%d)

[[ $@ ]] && journal="${@%%.adoc}.adoc" || journal="main.adoc"
path="$HOME/saveuriendir/$date/"

mkdir -p "$path"; cd "$path"
if [[ $call_mode ]]; then
  . $call_mode 
elif [[ $call_command ]]; then
  $call_command "$@"
else
  . $HOME/.config/journal/write
fi
