#!/usr/bin/env bash

export black=$(   tput setaf 0)
export red=$(     tput setaf 1)
export green=$(   tput setaf 2)
export yellow=$(  tput setaf 3)
export blue=$(    tput setaf 4)
export magenta=$( tput setaf 5)
export cyan=$(    tput setaf 6)
export white=$(   tput setaf 7)

export reverse=$(  tput smso)
export italic=$(   tput sitm)
export underline=$(tput smul)
export blink=$(    tput blink)
export bold=$(     tput bold)
export reset=$(    tput sgr0)
